/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji'

export interface Config {
  auth: {
    users: UserAuthOperations
  }
  blocks: {}
  collections: {
    articles: Article
    destinations: Destination
    faqs: Faq
    amenities: Amenity
    beds: Bed
    users: User
    media: Media
    'seo-media': SeoMedia
    guesthouses: Guesthouse
    rooms: Room
    'contact-persons': ContactPerson
    'social-media-platforms': SocialMediaPlatform
    'richtext-sections': RichtextSection
    'payload-kv': PayloadKv
    'payload-locked-documents': PayloadLockedDocument
    'payload-preferences': PayloadPreference
    'payload-migrations': PayloadMigration
  }
  collectionsJoins: {}
  collectionsSelect: {
    articles: ArticlesSelect<false> | ArticlesSelect<true>
    destinations: DestinationsSelect<false> | DestinationsSelect<true>
    faqs: FaqsSelect<false> | FaqsSelect<true>
    amenities: AmenitiesSelect<false> | AmenitiesSelect<true>
    beds: BedsSelect<false> | BedsSelect<true>
    users: UsersSelect<false> | UsersSelect<true>
    media: MediaSelect<false> | MediaSelect<true>
    'seo-media': SeoMediaSelect<false> | SeoMediaSelect<true>
    guesthouses: GuesthousesSelect<false> | GuesthousesSelect<true>
    rooms: RoomsSelect<false> | RoomsSelect<true>
    'contact-persons': ContactPersonsSelect<false> | ContactPersonsSelect<true>
    'social-media-platforms':
      | SocialMediaPlatformsSelect<false>
      | SocialMediaPlatformsSelect<true>
    'richtext-sections':
      | RichtextSectionsSelect<false>
      | RichtextSectionsSelect<true>
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>
    'payload-locked-documents':
      | PayloadLockedDocumentsSelect<false>
      | PayloadLockedDocumentsSelect<true>
    'payload-preferences':
      | PayloadPreferencesSelect<false>
      | PayloadPreferencesSelect<true>
    'payload-migrations':
      | PayloadMigrationsSelect<false>
      | PayloadMigrationsSelect<true>
  }
  db: {
    defaultIDType: string
  }
  fallbackLocale: null
  globals: {
    logos: Logo
    'home-page': HomePage
    'about-us-page': AboutUsPage
    'all-guesthouses-page': AllGuesthousesPage
  }
  globalsSelect: {
    logos: LogosSelect<false> | LogosSelect<true>
    'home-page': HomePageSelect<false> | HomePageSelect<true>
    'about-us-page': AboutUsPageSelect<false> | AboutUsPageSelect<true>
    'all-guesthouses-page':
      | AllGuesthousesPageSelect<false>
      | AllGuesthousesPageSelect<true>
  }
  locale: null
  user: User & {
    collection: 'users'
  }
  jobs: {
    tasks: unknown
    workflows: unknown
  }
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string
    password: string
  }
  login: {
    email: string
    password: string
  }
  registerFirstUser: {
    email: string
    password: string
  }
  unlock: {
    email: string
    password: string
  }
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "articles".
 */
export interface Article {
  id: string
  slug: string
  destination?: (string | null) | Destination
  guesthouse?: (string | null) | Guesthouse
  faq?: (string | null) | Faq
  featured?: boolean | null
  type: 'guide'
  author: string
  thumbnail: string | Media
  title: string
  excerpt: string
  body: {
    root: {
      type: string
      children: {
        type: any
        version: number
        [k: string]: unknown
      }[]
      direction: ('ltr' | 'rtl') | null
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | ''
      indent: number
      version: number
    }
    [k: string]: unknown
  }
  updatedAt: string
  createdAt: string
  _status?: ('draft' | 'published') | null
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "destinations".
 */
export interface Destination {
  id: string
  name: string
  slug: string
  image: string | Media
  seo: {
    meta: MetadataField
    open_graph: OpenGraphField
    twitter?: TwitterField
  }
  guides: {
    title: string
    description: string
    image: string | Media
    faq?: (string | null) | Faq
    meta: MetadataField
    open_graph: OpenGraphField
    twitter?: TwitterField
  }
  updatedAt: string
  createdAt: string
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: string
  alt: string
  prefix?: string | null
  updatedAt: string
  createdAt: string
  url?: string | null
  thumbnailURL?: string | null
  filename?: string | null
  mimeType?: string | null
  filesize?: number | null
  width?: number | null
  height?: number | null
  focalX?: number | null
  focalY?: number | null
  sizes?: {
    thumbnail?: {
      url?: string | null
      width?: number | null
      height?: number | null
      mimeType?: string | null
      filesize?: number | null
      filename?: string | null
    }
  }
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "MetadataField".
 */
export interface MetadataField {
  title: string
  description: string
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "OpenGraphField".
 */
export interface OpenGraphField {
  site_name: string
  title: string
  description: string
  image: string | SeoMedia
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "seo-media".
 */
export interface SeoMedia {
  id: string
  alt: string
  prefix?: string | null
  updatedAt: string
  createdAt: string
  url?: string | null
  thumbnailURL?: string | null
  filename?: string | null
  mimeType?: string | null
  filesize?: number | null
  width?: number | null
  height?: number | null
  focalX?: number | null
  focalY?: number | null
  sizes?: {
    thumbnail?: {
      url?: string | null
      width?: number | null
      height?: number | null
      mimeType?: string | null
      filesize?: number | null
      filename?: string | null
    }
    twitter?: {
      url?: string | null
      width?: number | null
      height?: number | null
      mimeType?: string | null
      filesize?: number | null
      filename?: string | null
    }
  }
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TwitterField".
 */
export interface TwitterField {
  creator?: string | null
  creatorId?: string | null
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "faqs".
 */
export interface Faq {
  id: string
  title: string
  items?:
    | {
        question: string
        answer: string
        id?: string | null
      }[]
    | null
  updatedAt: string
  createdAt: string
  _status?: ('draft' | 'published') | null
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "guesthouses".
 */
export interface Guesthouse {
  id: string
  name: string
  slug: string
  destination?: (string | null) | Destination
  faq?: (string | null) | Faq
  booking_platform: {
    name: 'NightsBridge'
    url: string
  }
  content: {
    heading: string
    description: string
    gallery: {
      heading: string
      description: string
    }
    images: {
      background_image: string | Media
      exterior: (string | Media)[]
      interior: (string | Media)[]
    }
    amenities: {
      heading: string
      description: string
      background_image: string | Media
      general_amenities: (string | Amenity)[]
    }
    rooms: {
      heading: string
      description: string
      people_icon: string | Media
      rooms?: (string | Room)[] | null
    }
  }
  business_details: {
    hours: {
      opening_time: '00:00' | '06:00' | '07:00' | '08:00' | '09:00' | '10:00'
      closing_time: '23:59' | '18:00' | '19:00' | '20:00' | '21:00' | '22:00'
    }
    check_in_out: {
      check_in_time:
        | 'T12:00:00+02:00'
        | 'T13:00:00+02:00'
        | 'T14:00:00+02:00'
        | 'T15:00:00+02:00'
        | 'T16:00:00+02:00'
      check_out_time:
        | 'T10:00:00+02:00'
        | 'T11:00:00+02:00'
        | 'T12:00:00+02:00'
        | 'T13:00:00+02:00'
        | 'T14:00:00+02:00'
    }
    geo: {
      latitude: string
      longitude: string
      maps_link: string
      maps_embed_url: string
    }
  }
  contact_details: {
    contact_persons?: (string | ContactPerson)[] | null
    address: {
      street: string
      suburb: string
      city: string
      province:
        | 'Eastern Cape'
        | 'Free State'
        | 'Gauteng'
        | 'KwaZulu-Natal'
        | 'Limpopo'
        | 'Mpumalanga'
        | 'Northern Cape'
        | 'North West'
        | 'Western Cape'
      postalCode: string
    }
    socials?:
      | {
          platform: string | SocialMediaPlatform
          url: string
          id?: string | null
        }[]
      | null
  }
  seo: {
    meta: MetadataField
    open_graph: OpenGraphField
    twitter?: TwitterField
  }
  updatedAt: string
  createdAt: string
  _status?: ('draft' | 'published') | null
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "amenities".
 */
export interface Amenity {
  id: string
  slug?: string | null
  featured: boolean
  name: string
  googleName?: string | null
  description?: string | null
  icon: string | Media
  price?: {
    unit_price?: number | null
    unit_type?: string | null
    on_request?: boolean | null
  }
  updatedAt: string
  createdAt: string
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "rooms".
 */
export interface Room {
  id: string
  slug?: string | null
  count: number
  base_price: number
  name: string
  description: string
  details: {
    sleeps_adults: number
    sleeps_children: number
    beds: {
      type: string | Bed
      quantity: number
      id?: string | null
    }[]
  }
  amenities: (string | Amenity)[]
  gallery: (string | Media)[]
  updatedAt: string
  createdAt: string
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "beds".
 */
export interface Bed {
  id: string
  name: string
  googleName: 'KING' | 'QUEEN' | 'DOUBLE' | 'SINGLE'
  icon: string | Media
  updatedAt: string
  createdAt: string
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "contact-persons".
 */
export interface ContactPerson {
  id: string
  name: string
  email: string
  phone: string
  position?: string | null
  updatedAt: string
  createdAt: string
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "social-media-platforms".
 */
export interface SocialMediaPlatform {
  id: string
  name: string
  icon: string | Media
  updatedAt: string
  createdAt: string
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: string
  roles?: ('admin' | 'editor')[] | null
  updatedAt: string
  createdAt: string
  email: string
  resetPasswordToken?: string | null
  resetPasswordExpiration?: string | null
  salt?: string | null
  hash?: string | null
  loginAttempts?: number | null
  lockUntil?: string | null
  sessions?:
    | {
        id: string
        createdAt?: string | null
        expiresAt: string
      }[]
    | null
  password?: string | null
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "richtext-sections".
 */
export interface RichtextSection {
  id: string
  heading: string
  content: {
    root: {
      type: string
      children: {
        type: any
        version: number
        [k: string]: unknown
      }[]
      direction: ('ltr' | 'rtl') | null
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | ''
      indent: number
      version: number
    }
    [k: string]: unknown
  }
  updatedAt: string
  createdAt: string
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: string
  key: string
  data:
    | {
        [k: string]: unknown
      }
    | unknown[]
    | string
    | number
    | boolean
    | null
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: string
  document?:
    | ({
        relationTo: 'articles'
        value: string | Article
      } | null)
    | ({
        relationTo: 'destinations'
        value: string | Destination
      } | null)
    | ({
        relationTo: 'faqs'
        value: string | Faq
      } | null)
    | ({
        relationTo: 'amenities'
        value: string | Amenity
      } | null)
    | ({
        relationTo: 'beds'
        value: string | Bed
      } | null)
    | ({
        relationTo: 'users'
        value: string | User
      } | null)
    | ({
        relationTo: 'media'
        value: string | Media
      } | null)
    | ({
        relationTo: 'seo-media'
        value: string | SeoMedia
      } | null)
    | ({
        relationTo: 'guesthouses'
        value: string | Guesthouse
      } | null)
    | ({
        relationTo: 'rooms'
        value: string | Room
      } | null)
    | ({
        relationTo: 'contact-persons'
        value: string | ContactPerson
      } | null)
    | ({
        relationTo: 'social-media-platforms'
        value: string | SocialMediaPlatform
      } | null)
    | ({
        relationTo: 'richtext-sections'
        value: string | RichtextSection
      } | null)
  globalSlug?: string | null
  user: {
    relationTo: 'users'
    value: string | User
  }
  updatedAt: string
  createdAt: string
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: string
  user: {
    relationTo: 'users'
    value: string | User
  }
  key?: string | null
  value?:
    | {
        [k: string]: unknown
      }
    | unknown[]
    | string
    | number
    | boolean
    | null
  updatedAt: string
  createdAt: string
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: string
  name?: string | null
  batch?: number | null
  updatedAt: string
  createdAt: string
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "articles_select".
 */
export interface ArticlesSelect<T extends boolean = true> {
  slug?: T
  destination?: T
  guesthouse?: T
  faq?: T
  featured?: T
  type?: T
  author?: T
  thumbnail?: T
  title?: T
  excerpt?: T
  body?: T
  updatedAt?: T
  createdAt?: T
  _status?: T
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "destinations_select".
 */
export interface DestinationsSelect<T extends boolean = true> {
  name?: T
  slug?: T
  image?: T
  seo?:
    | T
    | {
        meta?: T | MetadataFieldSelect<T>
        open_graph?: T | OpenGraphFieldSelect<T>
        twitter?: T | TwitterFieldSelect<T>
      }
  guides?:
    | T
    | {
        title?: T
        description?: T
        image?: T
        faq?: T
        meta?: T | MetadataFieldSelect<T>
        open_graph?: T | OpenGraphFieldSelect<T>
        twitter?: T | TwitterFieldSelect<T>
      }
  updatedAt?: T
  createdAt?: T
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "MetadataField_select".
 */
export interface MetadataFieldSelect<T extends boolean = true> {
  title?: T
  description?: T
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "OpenGraphField_select".
 */
export interface OpenGraphFieldSelect<T extends boolean = true> {
  site_name?: T
  title?: T
  description?: T
  image?: T
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TwitterField_select".
 */
export interface TwitterFieldSelect<T extends boolean = true> {
  creator?: T
  creatorId?: T
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "faqs_select".
 */
export interface FaqsSelect<T extends boolean = true> {
  title?: T
  items?:
    | T
    | {
        question?: T
        answer?: T
        id?: T
      }
  updatedAt?: T
  createdAt?: T
  _status?: T
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "amenities_select".
 */
export interface AmenitiesSelect<T extends boolean = true> {
  slug?: T
  featured?: T
  name?: T
  googleName?: T
  description?: T
  icon?: T
  price?:
    | T
    | {
        unit_price?: T
        unit_type?: T
        on_request?: T
      }
  updatedAt?: T
  createdAt?: T
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "beds_select".
 */
export interface BedsSelect<T extends boolean = true> {
  name?: T
  googleName?: T
  icon?: T
  updatedAt?: T
  createdAt?: T
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  roles?: T
  updatedAt?: T
  createdAt?: T
  email?: T
  resetPasswordToken?: T
  resetPasswordExpiration?: T
  salt?: T
  hash?: T
  loginAttempts?: T
  lockUntil?: T
  sessions?:
    | T
    | {
        id?: T
        createdAt?: T
        expiresAt?: T
      }
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T
  prefix?: T
  updatedAt?: T
  createdAt?: T
  url?: T
  thumbnailURL?: T
  filename?: T
  mimeType?: T
  filesize?: T
  width?: T
  height?: T
  focalX?: T
  focalY?: T
  sizes?:
    | T
    | {
        thumbnail?:
          | T
          | {
              url?: T
              width?: T
              height?: T
              mimeType?: T
              filesize?: T
              filename?: T
            }
      }
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "seo-media_select".
 */
export interface SeoMediaSelect<T extends boolean = true> {
  alt?: T
  prefix?: T
  updatedAt?: T
  createdAt?: T
  url?: T
  thumbnailURL?: T
  filename?: T
  mimeType?: T
  filesize?: T
  width?: T
  height?: T
  focalX?: T
  focalY?: T
  sizes?:
    | T
    | {
        thumbnail?:
          | T
          | {
              url?: T
              width?: T
              height?: T
              mimeType?: T
              filesize?: T
              filename?: T
            }
        twitter?:
          | T
          | {
              url?: T
              width?: T
              height?: T
              mimeType?: T
              filesize?: T
              filename?: T
            }
      }
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "guesthouses_select".
 */
export interface GuesthousesSelect<T extends boolean = true> {
  name?: T
  slug?: T
  destination?: T
  faq?: T
  booking_platform?:
    | T
    | {
        name?: T
        url?: T
      }
  content?:
    | T
    | {
        heading?: T
        description?: T
        gallery?:
          | T
          | {
              heading?: T
              description?: T
            }
        images?:
          | T
          | {
              background_image?: T
              exterior?: T
              interior?: T
            }
        amenities?:
          | T
          | {
              heading?: T
              description?: T
              background_image?: T
              general_amenities?: T
            }
        rooms?:
          | T
          | {
              heading?: T
              description?: T
              people_icon?: T
              rooms?: T
            }
      }
  business_details?:
    | T
    | {
        hours?:
          | T
          | {
              opening_time?: T
              closing_time?: T
            }
        check_in_out?:
          | T
          | {
              check_in_time?: T
              check_out_time?: T
            }
        geo?:
          | T
          | {
              latitude?: T
              longitude?: T
              maps_link?: T
              maps_embed_url?: T
            }
      }
  contact_details?:
    | T
    | {
        contact_persons?: T
        address?:
          | T
          | {
              street?: T
              suburb?: T
              city?: T
              province?: T
              postalCode?: T
            }
        socials?:
          | T
          | {
              platform?: T
              url?: T
              id?: T
            }
      }
  seo?:
    | T
    | {
        meta?: T | MetadataFieldSelect<T>
        open_graph?: T | OpenGraphFieldSelect<T>
        twitter?: T | TwitterFieldSelect<T>
      }
  updatedAt?: T
  createdAt?: T
  _status?: T
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "rooms_select".
 */
export interface RoomsSelect<T extends boolean = true> {
  slug?: T
  count?: T
  base_price?: T
  name?: T
  description?: T
  details?:
    | T
    | {
        sleeps_adults?: T
        sleeps_children?: T
        beds?:
          | T
          | {
              type?: T
              quantity?: T
              id?: T
            }
      }
  amenities?: T
  gallery?: T
  updatedAt?: T
  createdAt?: T
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "contact-persons_select".
 */
export interface ContactPersonsSelect<T extends boolean = true> {
  name?: T
  email?: T
  phone?: T
  position?: T
  updatedAt?: T
  createdAt?: T
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "social-media-platforms_select".
 */
export interface SocialMediaPlatformsSelect<T extends boolean = true> {
  name?: T
  icon?: T
  updatedAt?: T
  createdAt?: T
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "richtext-sections_select".
 */
export interface RichtextSectionsSelect<T extends boolean = true> {
  heading?: T
  content?: T
  updatedAt?: T
  createdAt?: T
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T
  data?: T
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T
  globalSlug?: T
  user?: T
  updatedAt?: T
  createdAt?: T
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T
  key?: T
  value?: T
  updatedAt?: T
  createdAt?: T
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T
  batch?: T
  updatedAt?: T
  createdAt?: T
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "logos".
 */
export interface Logo {
  id: string
  logo_dark: string | Media
  logo_light: string | Media
  minimal_dark: string | Media
  minimal_light: string | Media
  _status?: ('draft' | 'published') | null
  updatedAt?: string | null
  createdAt?: string | null
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "home-page".
 */
export interface HomePage {
  id: string
  hero: {
    background_image: string | Media
    title: string
    locations_link: {
      link_text: string
      link_url: string
    }
  }
  overview: {
    heading: string
    description: string
    images: (string | Media)[]
    features: {
      title: string
      description: string
      id?: string | null
    }[]
    locations_link: {
      link_text: string
      link_url: string
    }
  }
  featured: {
    heading: string
    subheading: string
    guesthouses: (string | Guesthouse)[]
  }
  faq?: (string | null) | Faq
  socials?:
    | {
        platform: string | SocialMediaPlatform
        url: string
        id?: string | null
      }[]
    | null
  contactPersons?: (string | ContactPerson)[] | null
  seo: {
    meta: MetadataField
    open_graph: OpenGraphField
    twitter?: TwitterField
  }
  _status?: ('draft' | 'published') | null
  updatedAt?: string | null
  createdAt?: string | null
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "about-us-page".
 */
export interface AboutUsPage {
  id: string
  hero: {
    heading: string
    sub_heading: string
  }
  overview: {
    title: string
    description: string
    image: string | Media
  }
  subsections?: (string | RichtextSection)[] | null
  seo: {
    meta: MetadataField
    open_graph: OpenGraphField
    twitter?: TwitterField
  }
  _status?: ('draft' | 'published') | null
  updatedAt?: string | null
  createdAt?: string | null
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "all-guesthouses-page".
 */
export interface AllGuesthousesPage {
  id: string
  content: {
    heading: string
    sub_heading: string
  }
  seo: {
    meta: MetadataField
    open_graph: OpenGraphField
    twitter?: TwitterField
  }
  _status?: ('draft' | 'published') | null
  updatedAt?: string | null
  createdAt?: string | null
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "logos_select".
 */
export interface LogosSelect<T extends boolean = true> {
  logo_dark?: T
  logo_light?: T
  minimal_dark?: T
  minimal_light?: T
  _status?: T
  updatedAt?: T
  createdAt?: T
  globalType?: T
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "home-page_select".
 */
export interface HomePageSelect<T extends boolean = true> {
  hero?:
    | T
    | {
        background_image?: T
        title?: T
        locations_link?:
          | T
          | {
              link_text?: T
              link_url?: T
            }
      }
  overview?:
    | T
    | {
        heading?: T
        description?: T
        images?: T
        features?:
          | T
          | {
              title?: T
              description?: T
              id?: T
            }
        locations_link?:
          | T
          | {
              link_text?: T
              link_url?: T
            }
      }
  featured?:
    | T
    | {
        heading?: T
        subheading?: T
        guesthouses?: T
      }
  faq?: T
  socials?:
    | T
    | {
        platform?: T
        url?: T
        id?: T
      }
  contactPersons?: T
  seo?:
    | T
    | {
        meta?: T | MetadataFieldSelect<T>
        open_graph?: T | OpenGraphFieldSelect<T>
        twitter?: T | TwitterFieldSelect<T>
      }
  _status?: T
  updatedAt?: T
  createdAt?: T
  globalType?: T
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "about-us-page_select".
 */
export interface AboutUsPageSelect<T extends boolean = true> {
  hero?:
    | T
    | {
        heading?: T
        sub_heading?: T
      }
  overview?:
    | T
    | {
        title?: T
        description?: T
        image?: T
      }
  subsections?: T
  seo?:
    | T
    | {
        meta?: T | MetadataFieldSelect<T>
        open_graph?: T | OpenGraphFieldSelect<T>
        twitter?: T | TwitterFieldSelect<T>
      }
  _status?: T
  updatedAt?: T
  createdAt?: T
  globalType?: T
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "all-guesthouses-page_select".
 */
export interface AllGuesthousesPageSelect<T extends boolean = true> {
  content?:
    | T
    | {
        heading?: T
        sub_heading?: T
      }
  seo?:
    | T
    | {
        meta?: T | MetadataFieldSelect<T>
        open_graph?: T | OpenGraphFieldSelect<T>
        twitter?: T | TwitterFieldSelect<T>
      }
  _status?: T
  updatedAt?: T
  createdAt?: T
  globalType?: T
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "GoogleMapBlock".
 */
export interface GoogleMapBlock {
  title?: string | null
  maps_embed_url: string
  maps_link?: string | null
  id?: string | null
  blockName?: string | null
  blockType: 'googleMap'
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown
}

declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}
